#!/bin/sh
opkg update

echo ""
echo "    ***   PLEASE INSTALL SERVICEAPP         ***"

opkg install enigma2-plugin-systemplugins-serviceapp

echo ""
echo "    ***  START Streamlink[-27] INSTALLATION  ***"

opkg remove python-streamlink
curl https://github.com/PURE2-Team/3rdparty-plugins/raw/master/python-streamlink_1.27.1.0.r0_mod_all.ipk -Lko /tmp/python-streamlink_1.27.1.0.r0_mod_all.ipk > /dev/null
opkg --force-overwrite install /tmp/python-streamlink_1.27.1.0.r0_mod_all.ipk
opkg install --force-reinstall --force-depends /tmp/python-streamlink_1.27.1.0.r0_mod_all.ipk


echo ""
echo "    *** Streamlink[-27] INSTALLATION END ***"
reboot
